### ISSUE TITLE
Any way to get the collector to talk to raintank.io through a proxy?

### ISSUE THREAD

**Issue by ragesaq** [monitoringartist/docker-raintank-collector#1]

**Comment by jangaraj** [comment]
Plase create feature request https://github.com/raintank/raintank-collector  Raintank is rewriting collector code, so they can include proxying in their code. However probably better solution is to configure docker to use proxy (typical usage for enterprise environment) - http://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy
